# Generated by Django 6.0.5 on 2026-05-15 14:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('target', models.CharField(max_length=200)),
                ('achieved', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('on_track', 'On Track'), ('achieved', 'Achieved'), ('missed', 'Missed'), ('in_progress', 'In Progress')], default='in_progress', max_length=20)),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_period', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half Yearly'), ('annual', 'Annual')], default='monthly', max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('rating', models.IntegerField(choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=3)),
                ('attendance_score', models.IntegerField(default=0, help_text='Out of 20')),
                ('productivity_score', models.IntegerField(default=0, help_text='Out of 20')),
                ('quality_score', models.IntegerField(default=0, help_text='Out of 20')),
                ('teamwork_score', models.IntegerField(default=0, help_text='Out of 20')),
                ('communication_score', models.IntegerField(default=0, help_text='Out of 20')),
                ('comments', models.TextField(blank=True)),
                ('self_evaluation', models.TextField(blank=True)),
                ('goals_achieved', models.TextField(blank=True)),
                ('goals_next_period', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
