# Generated by Django 6.0.5 on 2026-06-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_device_id_customuser_device_registered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='device_last_ip',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AddField(
            model_name='customuser',
            name='device_last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
