# Generated by Django 6.0.5 on 2026-06-15 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_current_session_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
