# Generated by Django 6.0.5 on 2026-06-15 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_start', models.TimeField(help_text='Shift start time, e.g. 09:00')),
                ('work_end', models.TimeField(help_text='Shift end time, e.g. 18:00')),
                ('checkin_open', models.TimeField(help_text='Earliest allowed check-in time, e.g. 08:55')),
                ('checkout_max', models.TimeField(help_text='Latest allowed check-out / auto-logout time, e.g. 18:30')),
                ('working_days', models.CharField(default='0,1,2,3,4', help_text='Comma-separated weekday ints (Mon=0 … Sun=6).', max_length=20)),
                ('breaks', models.JSONField(blank=True, default=list, help_text='List of {start,end,label,deductible} break windows.')),
                ('break_early_restart_minutes', models.PositiveIntegerField(default=5)),
                ('commission_enabled', models.BooleanField(default=True, help_text='Show/allow the Sales Commission feature.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_schedule', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
