# Generated by Django 6.0.5 on 2026-06-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_tenantschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantschedule',
            name='enforce_working_hours',
            field=models.BooleanField(default=False, help_text='When on, employees may sign in to the portal at any time but can only perform attendance actions (check-in, check-out, resume work) during the allowed working-hours window. Outside that window every action is blocked with a notice.'),
        ),
    ]
