# Generated by Django 6.0.5 on 2026-06-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarydeduction',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual (admin)'), ('attendance', 'Auto (attendance)')], default='manual', max_length=20),
        ),
    ]
