# Generated by Django 6.0.5 on 2026-05-15 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_number', models.IntegerField()),
                ('scheduled_end', models.TimeField()),
                ('resumed_at', models.DateTimeField()),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='break_restarts', to='attendance.attendance')),
            ],
            options={
                'ordering': ['break_number'],
                'unique_together': {('attendance', 'break_number')},
            },
        ),
    ]
